insert into T_ADS_FACT_LCA_PROC_DATA(REC_ID, BATCH_NUMBER, START_YM, END_YM, LCA_PROC_CODE, LCA_PROC_NAME, PRODUCT_CODE,
                                     PRODUCT_NAME, LCA_DATA_ITEM_CAT_CODE, LCA_DATA_ITEM_CAT_NAME, LCA_DATA_ITEM_CODE,
                                     LCA_DATA_ITEM_NAME, VALUE, UNIT, INDEX_CODE, COMPANY_CODE)
select HEX(RAND()),
       BATCH_NUMBER || '_GREEN20',
       START_YM,
       END_YM,
       LCA_PROC_CODE,
       LCA_PROC_NAME,
       PRODUCT_CODE,
       PRODUCT_NAME,
       LCA_DATA_ITEM_CAT_CODE,
       LCA_DATA_ITEM_CAT_NAME,
       LCA_DATA_ITEM_CODE,
       LCA_DATA_ITEM_NAME,
       VALUE,
       UNIT,
       INDEX_CODE,
       COMPANY_CODE
from T_ADS_FACT_LCA_PROC_DATA
where BATCH_NUMBER IN
      ('20250920250920260120YS', '20251020251020260120YS', '20251120251120260120YS', '20251220251220260120YS')
  and COMPANY_CODE = 'TM'
  and PRODUCT_CODE <> 'X4070'
  and LCA_DATA_ITEM_CODE <> 'X4070';


insert into T_ADS_FACT_LCA_PROC_DATA(REC_ID, BATCH_NUMBER, START_YM, END_YM, LCA_PROC_CODE, LCA_PROC_NAME, PRODUCT_CODE,
                                     PRODUCT_NAME, LCA_DATA_ITEM_CAT_CODE, LCA_DATA_ITEM_CAT_NAME, LCA_DATA_ITEM_CODE,
                                     LCA_DATA_ITEM_NAME, VALUE, UNIT, INDEX_CODE, COMPANY_CODE)
select HEX(RAND()),
       BATCH_NUMBER || '_GREEN20',
       START_YM,
       END_YM,
       LCA_PROC_CODE,
       LCA_PROC_NAME,
       PRODUCT_CODE,
       PRODUCT_NAME,
       LCA_DATA_ITEM_CAT_CODE,
       LCA_DATA_ITEM_CAT_NAME,
       LCA_DATA_ITEM_CODE,
       LCA_DATA_ITEM_NAME,
       VALUE * 0.8,
       UNIT,
       INDEX_CODE,
       COMPANY_CODE
from T_ADS_FACT_LCA_PROC_DATA
where BATCH_NUMBER IN
      ('20250920250920260120YS', '20251020251020260120YS', '20251120251120260120YS', '20251220251220260120YS')
  and COMPANY_CODE = 'TM'
  and PRODUCT_CODE <> 'X4070'
  and LCA_DATA_ITEM_CODE = 'X4070';

insert into T_ADS_FACT_LCA_PROC_DATA(REC_ID, BATCH_NUMBER, START_YM, END_YM, LCA_PROC_CODE, LCA_PROC_NAME, PRODUCT_CODE,
                                     PRODUCT_NAME, LCA_DATA_ITEM_CAT_CODE, LCA_DATA_ITEM_CAT_NAME, LCA_DATA_ITEM_CODE,
                                     LCA_DATA_ITEM_NAME, VALUE, UNIT, INDEX_CODE, COMPANY_CODE)
select HEX(RAND()),
       BATCH_NUMBER || '_GREEN20',
       START_YM,
       END_YM,
       LCA_PROC_CODE,
       LCA_PROC_NAME,
       PRODUCT_CODE,
       PRODUCT_NAME,
       LCA_DATA_ITEM_CAT_CODE,
       LCA_DATA_ITEM_CAT_NAME,
       '50110',
       '电-外购-光伏电',
       VALUE * 0.2,
       UNIT,
       INDEX_CODE,
       COMPANY_CODE
from T_ADS_FACT_LCA_PROC_DATA
where BATCH_NUMBER IN
      ('20250920250920260120YS', '20251020251020260120YS', '20251120251120260120YS', '20251220251220260120YS')
  and COMPANY_CODE = 'TM'
  and PRODUCT_CODE <> 'X4070'
  and LCA_DATA_ITEM_CODE = 'X4070';


insert into T_ADS_FACT_LCA_PROC_DATA(REC_ID, BATCH_NUMBER, START_YM, END_YM, LCA_PROC_CODE, LCA_PROC_NAME, PRODUCT_CODE,
                                     PRODUCT_NAME, LCA_DATA_ITEM_CAT_CODE, LCA_DATA_ITEM_CAT_NAME, LCA_DATA_ITEM_CODE,
                                     LCA_DATA_ITEM_NAME, VALUE, UNIT, INDEX_CODE, COMPANY_CODE)
select HEX(RAND()),
       BATCH_NUMBER || '_GREEN20',
       START_YM,
       END_YM,
       LCA_PROC_CODE,
       LCA_PROC_NAME,
       PRODUCT_CODE,
       PRODUCT_NAME,
       LCA_DATA_ITEM_CAT_CODE,
       LCA_DATA_ITEM_CAT_NAME,
       LCA_DATA_ITEM_CODE,
       LCA_DATA_ITEM_NAME,
       VALUE,
       UNIT,
       INDEX_CODE,
       COMPANY_CODE
from T_ADS_FACT_LCA_PROC_DATA
where BATCH_NUMBER IN
      ('20250920250920260120YS', '20251020251020260120YS', '20251120251120260120YS', '20251220251220260120YS')
  and COMPANY_CODE = 'TM'
  and PRODUCT_CODE = 'X4070';




CALL BG00MAC102.P_ADS_FACT_LCA_SUBCLASS_CALC(
        V_PCR => 'NORM',
        V_COMPANY_CODE => 'TM',
        V_START_YM => NULL,
        V_END_YM => NULL,
        V_FACTOR_YEAR => '2025',
        V_FACTOR_VERSION => 'NORM_Ecoinvent3.11',
        V_AUTO_BATCH => TRUE,
        V_BATCH_SUFFIX => 'GREEN20',
        V_MAIN_CAT_TAB_NAME => 'T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_RESULT',
        V_MAIN_CAT_BATCH_NUMBER => NULL,
        V_SUBCLASS_TAB_NAME => 'T_ADS_FACT_LCA_BGMG_CR0001_2025_NEW_0202',
        V_SUBCLASS_RESULT_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_BGMG_CR0001_2025_NEW_0202_GREEN20',
        V_SUBCLASS_RESULT_DIST_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_BGMG_CR0001_2025_NEW_0202_GREEN20_DIST',
        V_SUBCLASS_FILTER_CONDITION => 'AND MAT_TRACK_NO LIKE ''%#_20'' ESCAPE ''#'''
     );