update BG00MAC102.T_ADS_WH_LCA_MAT_DATA
set HOTVALUE_UNIT = 'MJ/kg'
where HOTVALUE_UNIT = '5.0'
   or HOTVALUE_UNIT = '5';

update BG00MAC102.T_ADS_WH_LCA_MAT_DATA
set HOTVALUE_UNIT = 'MJ/m3'
where HOTVALUE_UNIT = '6'
   or HOTVALUE_UNIT = '6.0';

update BG00MAC102.T_ADS_WH_LCA_MAT_DATA
set HOTVALUE = NULL
where HOTVALUE = '0.0';

update BG00MAC102.T_ADS_WH_LCA_MAT_DATA
set HOTVALUE_UNIT = NULL
where HOTVALUE_UNIT = '0.0';

update BG00MAC102.T_ADS_WH_LCA_MAT_DATA
set DISCH_COEFF_UNIT = 'kgCO2/kg'
where DISCH_COEFF_UNIT = 'kg CO2eq/kg'
   or DISCH_COEFF_UNIT = '1';

update BG00MAC102.T_ADS_WH_LCA_MAT_DATA
set DISCH_COEFF_UNIT = 'kgCO2/m3'
where DISCH_COEFF_UNIT = 'kg CO2eq/m3'
   or DISCH_COEFF_UNIT = '2';


-- ALTER TABLE BG00MAC102.T_ADS_WH_LCA_MAT_DATA
--     ALTER COLUMN HOTVALUE SET DATA TYPE DECIMAL(30, 10);

