create table BG00MAC102.T_ADS_WH_LCA_FACTOR_LIBRARY_LCI_LOOKUP
(
    REC_ID           VARCHAR(32) default NULL,
    LCI_ELEMENT_ID   VARCHAR(100),
    LCI_ELEMENT_NAME VARCHAR(500)
)
    distribute by hash (REC_ID);

comment on table BG00MAC102.T_ADS_WH_LCA_FACTOR_LIBRARY_LCI_LOOKUP is 'LCI因子基本流对照表';

comment on column BG00MAC102.T_ADS_WH_LCA_FACTOR_LIBRARY_LCI_LOOKUP.REC_ID is '记录识别码';

comment on column BG00MAC102.T_ADS_WH_LCA_FACTOR_LIBRARY_LCI_LOOKUP.LCI_ELEMENT_ID is '基本流ID';

comment on column BG00MAC102.T_ADS_WH_LCA_FACTOR_LIBRARY_LCI_LOOKUP.LCI_ELEMENT_NAME is '基本流名称';

