drop table BG00MAC102.T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_DIST;

create table BG00MAC102.T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_DIST
(
    REC_ID           VARCHAR(64),
    BATCH_NUMBER     VARCHAR(64),
    START_YM         VARCHAR(8),
    END_YM           VARCHAR(8),
    COMPANY_CODE     VARCHAR(8),
    SOURCE_PROC_KEY  VARCHAR(64),
    SOURCE_PROC_CODE VARCHAR(64),
    SOURCE_PROC_NAME VARCHAR(256),
    TARGET_PROC_KEY  VARCHAR(64),
    TARGET_PROC_CODE VARCHAR(64),
    TARGET_PROC_NAME VARCHAR(256),
    PRODUCT_CODE     VARCHAR(64),
    PRODUCT_NAME     VARCHAR(128),
    ITEM_CAT_CODE    VARCHAR(10),
    ITEM_CAT_NAME    VARCHAR(50),
    ITEM_CODE        VARCHAR(256),
    ITEM_NAME        VARCHAR(256),
    LCI_ELEMENT_CODE VARCHAR(256),
    TYPE             VARCHAR(256),
    LOAD             DECIMAL(16, 10),
    REC_CREATOR      VARCHAR(32),
    REC_CREATE_TIME  VARCHAR(32),
    REC_REVISOR      VARCHAR(32),
    REC_REVISE_TIME  VARCHAR(32)
)
    distribute by hash (REC_ID);

comment on table BG00MAC102.T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_DIST is '普通用钢LCA大类中间分布';
