create table BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI_LOOKUP
(
    REC_ID           VARCHAR(32) default NULL,
    LCI_ELEMENT      VARCHAR(100),
    LCI_ELEMENT_NAME VARCHAR(500)
)
    distribute by hash (REC_ID);

comment on table BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI_LOOKUP is 'LCI因子名称中英文对照表';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI_LOOKUP.REC_ID is '记录识别码';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI_LOOKUP.LCI_ELEMENT is 'LCI因子';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI_LOOKUP.LCI_ELEMENT_NAME is 'LCI因子名称';