create table BG00MAC102.T_ADS_FACT_LCA_MAIN_CAT_MATRIX_ENERGY
(
    REC_ID           VARCHAR(64),
    BATCH_NUMBER     VARCHAR(64),
    START_YM         VARCHAR(8),
    END_YM           VARCHAR(8),
    COMPANY_CODE     VARCHAR(8),
    PROC_KEY         VARCHAR(64),
    PROC_NAME        VARCHAR(256),
    ITEM_CODE        VARCHAR(64),
    ITEM_NAME        VARCHAR(64),
    ITEM_CAT_NAME    VARCHAR(64),
    SOURCE_PROC_KEY  VARCHAR(64),
    SOURCE_PROC_NAME VARCHAR(256),
    UNIT_COST        DECIMAL(24, 10),
    INV              VARCHAR(8),
    REC_CREATOR      VARCHAR(32),
    REC_CREATE_TIME  VARCHAR(32),
    REC_REVISOR      VARCHAR(32),
    REC_REVISE_TIME  VARCHAR(32)
)
    distribute by hash (REC_ID);

comment on table BG00MAC102.T_ADS_FACT_LCA_MAIN_CAT_MATRIX_ENERGY is 'LCA大类能辅矩阵';