CREATE TABLE BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_NEW
(
    REC_ID                                VARCHAR(32) DEFAULT NULL,
    START_TIME                            VARCHAR(8)  DEFAULT NULL,
    END_TIME                              VARCHAR(8)  DEFAULT NULL,
    COMPANY_CODE                          VARCHAR(10),
    DATA_ITEM_NAME                        VARCHAR(100),
    BACKGROUND_DATA                       VARCHAR(500),
    NONRENEWABLE_SECONDARY_FUEL           DECIMAL(25, 20),
    ADP_FOSSIL_FUELS                      DECIMAL(25, 20),
    ADP_MINERAL_ELEMENTS                  DECIMAL(25, 20),
    POCP                                  DECIMAL(25, 20),
    SECONDARY_MATERIAL_UTILIZATION_VOLUME DECIMAL(25, 20),
    RADIOACTIVE_SOLID_WASTE_DISPOSAL      DECIMAL(25, 20),
    EP                                    DECIMAL(25, 20),
    RENEWABLE_SECONDARY_FUEL              DECIMAL(25, 20),
    ODP                                   DECIMAL(25, 20),
    GWP                                   DECIMAL(25, 20),
    GWP_FOSSIL_ENERGY                     DECIMAL(25, 20),
    GWP_BIOMASS                           DECIMAL(25, 20),
    GWP_LAND_USE                          DECIMAL(25, 20),
    AP                                    DECIMAL(25, 20),
    HAZARDOUS_SOLID_WASTE_DISPOSAL        DECIMAL(25, 20),
    NONHAZARDOUS_SOLID_WASTE_DISPOSAL     DECIMAL(25, 20),
    FRESHWATER_CONSUMPTION                DECIMAL(25, 20),
    PRIMARY_ENERGY_NONRENEWABLE_SUM       DECIMAL(25, 20),
    PRIMARY_ENERGY_NONRENEWABLE_CARRIER   DECIMAL(25, 20),
    PRIMARY_ENERGY_NONRENEWABLE_MATERIALS DECIMAL(25, 20),
    PRIMARY_ENERGY_RENEWABLE_SUM          DECIMAL(25, 20),
    PRIMARY_ENERGY_RENEWABLE_CARRIER      DECIMAL(25, 20),
    PRIMARY_ENERGY_RENEWABLE_MATERIALS    DECIMAL(25, 20),
    SOURCE                                VARCHAR(50),
    U1_DESC                               VARCHAR(50),
    U1_FAC                                DECIMAL(20, 10),
    U2_DESC                               VARCHAR(50),
    U2_FAC                                DECIMAL(20, 10),
    U3_START_TIME                         VARCHAR(4),
    U3_END_TIME                           VARCHAR(4),
    U3_FAC                                DECIMAL(20, 10),
    U4_DESC                               VARCHAR(50),
    U4_FAC                                DECIMAL(20, 10),
    U5_DESC                               VARCHAR(5000),
    U5_FAC                                DECIMAL(20, 10),
    UB_DESC                               VARCHAR(50),
    UB_FAC                                DECIMAL(20, 10),
    UNCERTAIN_POSSIBL                     DECIMAL(25, 20),
    TIRAD_START_TIME                      VARCHAR(4),
    TIRAD_END_TIME                        VARCHAR(4),
    TIRAD_IND                             DECIMAL(20, 10),
    TERAD_IND_DESC                        VARCHAR(5000),
    TERAD_IND                             DECIMAL(20, 10),
    GERAD_IND_DESC                        VARCHAR(50),
    GERAD_IND                             DECIMAL(20, 10),
    DQR                                   DECIMAL(20, 10),
    UUID                                  VARCHAR(32)
)
    IN BG00MAC102
    DISTRIBUTE BY HASH (REC_ID)
    COMPRESS YES ADAPTIVE
    ORGANIZE BY ROW;

ALTER TABLE BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_NEW
    DATA CAPTURE NONE
    PCTFREE 0
    LOCKSIZE ROW
    APPEND OFF
    NOT VOLATILE;

COMMENT ON TABLE BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_NEW IS '股份背景数据评分';

COMMENT ON BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_NEW (
    REC_ID IS '记录识别码',
    START_TIME IS '开始时间',
    END_TIME IS '结束时间',
    COMPANY_CODE IS '公司代码',
    DATA_ITEM_NAME IS '数据项名',
    BACKGROUND_DATA IS '背景数据',
    NONRENEWABLE_SECONDARY_FUEL IS '不可再生二次燃料',
    ADP_FOSSIL_FUELS IS '不可再生资源耗竭潜力（ADP）-化石燃料',
    ADP_MINERAL_ELEMENTS IS '不可再生资源耗竭潜力（ADP）-矿物元素',
    POCP IS '对流层臭氧生成潜力(POCP)',
    SECONDARY_MATERIAL_UTILIZATION_VOLUME IS '二次材料利用量',
    RADIOACTIVE_SOLID_WASTE_DISPOSAL IS '放射性固体废弃物处置',
    EP IS '富营养化潜力(EP)',
    RENEWABLE_SECONDARY_FUEL IS '可再生二次燃料',
    ODP IS '平流层臭氧层消耗潜力（ODP）',
    GWP IS '全球变暖潜力(GWP100):合计',
    GWP_FOSSIL_ENERGY IS '全球变暖潜力(GWP100):化石能源',
    GWP_BIOMASS IS '全球变暖潜力(GWP100):生物质',
    GWP_LAND_USE IS '全球变暖潜力(GWP100):土地利用和土地用途改变',
    AP IS '酸化潜力(AP)',
    HAZARDOUS_SOLID_WASTE_DISPOSAL IS '危险固体废弃物处置',
    NONHAZARDOUS_SOLID_WASTE_DISPOSAL IS '无危险固体废弃物处置',
    FRESHWATER_CONSUMPTION IS '新水耗量',
    PRIMARY_ENERGY_NONRENEWABLE_SUM IS '一次能源-不可再生能源:合计',
    PRIMARY_ENERGY_NONRENEWABLE_CARRIER IS '一次能源-不可再生能源:用作能量载体',
    PRIMARY_ENERGY_NONRENEWABLE_MATERIALS IS '一次能源-不可再生能源:用作原材料',
    PRIMARY_ENERGY_RENEWABLE_SUM IS '一次能源-可再生能源:合计',
    PRIMARY_ENERGY_RENEWABLE_CARRIER IS '一次能源-可再生能源:用作能量载体',
    PRIMARY_ENERGY_RENEWABLE_MATERIALS IS '一次能源-可再生能源:用作原材料',
    SOURCE IS '来源',
    U1_DESC IS '精度描述',
    U1_FAC IS '精度因子',
    U2_DESC IS '完整性描述',
    U2_FAC IS '完整性因子',
    U3_START_TIME IS '时间代表性开始时间',
    U3_END_TIME IS '时间代表性结束时间',
    U3_FAC IS '时间代表性因子',
    U4_DESC IS '地理代表性描述',
    U4_FAC IS '地理代表性因子',
    U5_DESC IS '技术代表性描述',
    U5_FAC IS '技术代表性因子',
    UB_DESC IS '基础不确定性描述',
    UB_FAC IS '基础不确定性因子',
    UNCERTAIN_POSSIBL IS '不确定可能性',
    TIRAD_START_TIME IS '时间代表性开始时间',
    TIRAD_END_TIME IS '时间代表性结束时间',
    TIRAD_IND IS '时间代表性',
    TERAD_IND_DESC IS '技术代表性描述',
    TERAD_IND IS '技术代表性',
    GERAD_IND_DESC IS '地理代表性描述',
    GERAD_IND IS '地理代表性',
    DQR IS '耐久性质量与可靠性' );


