create table BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI
(
    REC_ID            VARCHAR(32) default NULL,
    YEAR              VARCHAR(8),
    COMPANY_CODE      VARCHAR(10),
    DATA_ITEM_NAME    VARCHAR(100),
    BACKGROUND_DATA   VARCHAR(500),
    SOURCE            VARCHAR(50),
    UUID              VARCHAR(32),
    LCI_ELEMENT       VARCHAR(100),
    LCI_ELEMENT_NAME  VARCHAR(500),
    LCI_ELEMENT_VALUE DECIMAL(25, 20),
    U1_DESC           VARCHAR(50),
    U1_FAC            DECIMAL(20, 10),
    U2_DESC           VARCHAR(50),
    U2_FAC            DECIMAL(20, 10),
    U3_START_TIME     VARCHAR(4),
    U3_END_TIME       VARCHAR(4),
    U3_FAC            DECIMAL(20, 10),
    U4_DESC           VARCHAR(50),
    U4_FAC            DECIMAL(20, 10),
    U5_DESC           VARCHAR(5000),
    U5_FAC            DECIMAL(20, 10),
    UB_DESC           VARCHAR(50),
    UB_FAC            DECIMAL(20, 10),
    UNCERTAIN_POSSIBL DECIMAL(25, 20),
    TIRAD_START_TIME  VARCHAR(4),
    TIRAD_END_TIME    VARCHAR(4),
    TIRAD_IND         DECIMAL(20, 10),
    TERAD_IND_DESC    VARCHAR(5000),
    TERAD_IND         DECIMAL(20, 10),
    GERAD_IND_DESC    VARCHAR(50),
    GERAD_IND         DECIMAL(20, 10),
    DQR               DECIMAL(20, 10)
)
    distribute by hash (REC_ID);

comment on table BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI is '股份LCI背景因子及评分';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.REC_ID is '记录识别码';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.YEAR is '年份';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.COMPANY_CODE is '公司代码';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.DATA_ITEM_NAME is '数据项名';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.BACKGROUND_DATA is '背景数据';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.SOURCE is '来源';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.UUID is '识别码';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.LCI_ELEMENT is '识别码';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.LCI_ELEMENT_NAME is '识别码';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.LCI_ELEMENT_VALUE is '识别码';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U1_DESC is '精度描述';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U1_FAC is '精度因子';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U2_DESC is '完整性描述';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U2_FAC is '完整性因子';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U3_START_TIME is '时间代表性开始时间';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U3_END_TIME is '时间代表性结束时间';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U3_FAC is '时间代表性因子';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U4_DESC is '地理代表性描述';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U4_FAC is '地理代表性因子';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U5_DESC is '技术代表性描述';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.U5_FAC is '技术代表性因子';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.UB_DESC is '基础不确定性描述';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.UB_FAC is '基础不确定性因子';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.UNCERTAIN_POSSIBL is '不确定可能性';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.TIRAD_START_TIME is '时间代表性开始时间';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.TIRAD_END_TIME is '时间代表性结束时间';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.TIRAD_IND is '时间代表性';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.TERAD_IND_DESC is '技术代表性描述';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.TERAD_IND is '技术代表性';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.GERAD_IND_DESC is '地理代表性描述';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.GERAD_IND is '地理代表性';

comment on column BG00MAC102.T_ADS_WH_PROC_BACKGROUND_UNCERT_ASSES_LCI.DQR is '耐久性质量与可靠性';

