SET CURRENT SCHEMA = BG00MAC102;

CREATE TABLE BG00MAC102.T_ADS_FACT_LCA_SI0001_2024
(
    REC_ID          VARCHAR(50),
    MAT_NO          VARCHAR(20),
    MAT_TRACK_NO    VARCHAR(20),
    MAT_SEQ_NO      BIGINT,
    FAMILY_CODE     VARCHAR(1000),
    UNIT_CODE       VARCHAR(10),
    UNIT_NAME       VARCHAR(256),
    TYPE_CODE       VARCHAR(20),
    TYPE_NAME       VARCHAR(200),
    UNITM_AC        VARCHAR(20),
    ITEM_CODE       VARCHAR(100),
    ITEM_NAME       VARCHAR(256),
    INDEX_ID        VARCHAR(100),
    VALUE           DECIMAL(16, 6),
    REC_CREATE_TIME VARCHAR(24),
    REC_CREATOR     VARCHAR(50),
    REC_REVISE_TIME VARCHAR(24),
    REC_REVISOR     VARCHAR(50),
    BATCH_NUMBER    VARCHAR(50)
)
    IN BG00MAC102
    DISTRIBUTE BY HASH (REC_ID)
    COMPRESS YES ADAPTIVE
    ORGANIZE BY ROW;

ALTER TABLE BG00MAC102.T_ADS_FACT_LCA_SI0001_2024
    DATA CAPTURE NONE
    PCTFREE 0
    LOCKSIZE ROW
    APPEND OFF
    NOT VOLATILE;

COMMENT ON TABLE BG00MAC102.T_ADS_FACT_LCA_SI0001_2024 IS '硅钢物料跟踪明细-工序数据';

COMMENT ON BG00MAC102.T_ADS_FACT_LCA_SI0001_2024 (
    REC_ID IS '编号',
    MAT_NO IS '材料号',
    MAT_TRACK_NO IS '材料跟踪号',
    MAT_SEQ_NO IS '材料顺序',
    FAMILY_CODE IS '亲属码',
    UNIT_CODE IS '工序代码',
    UNIT_NAME IS '工序名称',
    TYPE_CODE IS '数据项分类代码',
    TYPE_NAME IS '数据项分类名称',
    UNITM_AC IS '单位',
    ITEM_CODE IS '数据项代码',
    ITEM_NAME IS '数据项名称',
    INDEX_ID IS 'ID',
    VALUE IS '值',
    REC_CREATE_TIME IS '创建时间',
    REC_CREATOR IS '创建人',
    REC_REVISE_TIME IS '修改人',
    REC_REVISOR IS '修改时间' );

COMMIT;

RUNSTATS ON TABLE BG00MAC102.T_ADS_FACT_LCA_SI0001_2024
	ALLOW WRITE ACCESS;

COMMIT;