call BG00MAC102.P_ADS_FACT_LCA_SUBCLASS_SEQ_CALC(
        V_COMPANY_CODE => 'TA',
        V_START_DATE => '202401',
        V_END_DATE => '202412',
        V_FACTOR_YEAR => '2024',
        V_SUBCLASS_TAB_NAME => 'T_ADS_FACT_LCA_SI0001_2024',
        V_SUB_BATCH_NUMBER => 'MX202401'
     );

SELECT MAT_TRACK_NO, MAT_SEQ_NO, FAMILY_CODE, UNIT_CODE, SUM(C_CYCLE)
FROM T_ADS_FACT_LCA_SUBCLASS_RESULT_DIST_PARALLEL
GROUP BY MAT_TRACK_NO, MAT_SEQ_NO, FAMILY_CODE, UNIT_CODE
ORDER BY MAT_TRACK_NO, FAMILY_CODE, MAT_SEQ_NO;

SELECT MAT_TRACK_NO, MAT_SEQ_NO, FAMILY_CODE, UNIT_CODE, C_CYCLE
FROM T_ADS_FACT_LCA_SUBCLASS_RESULT
ORDER BY MAT_TRACK_NO, FAMILY_CODE, MAT_SEQ_NO;


SELECT HEX(RAND()),
       SUBCLASS_TAB_NAME,
       '',
       BATCH_NUMBER,
       '',
       MAT_NO,
       MAT_TRACK_NO,
       MAT_SEQ_NO,
       FAMILY_CODE,
       UNIT_CODE,
       UNIT_NAME,
       PRODUCT_CODE,
       PRODUCT_NAME,
       PRODUCT_VALUE,
       SUM(C1),
       SUM(C2),
       SUM(C3),
       SUM(C4),
       SUM(C5),
       SUM(C1) + SUM(C2),
       SUM(C3) + SUM(C4) + SUM(C5),
       SUM(C1) + SUM(C2) + SUM(C3) + SUM(C4) + SUM(C5),
       NULL,
       TO_CHAR(CURRENT_TIMESTAMP, 'yyyyMMddHH24MI'),
       NULL,
       NULL
FROM T_ADS_TEMP_LCA_SUBCLASS_SEQ_CALC_RESULT_DIST_PARALLEL
GROUP BY SUBCLASS_TAB_NAME, BATCH_NUMBER, MAT_NO, MAT_TRACK_NO, MAT_SEQ_NO, FAMILY_CODE, UNIT_CODE, UNIT_NAME,
         PRODUCT_CODE, PRODUCT_NAME, PRODUCT_VALUE
ORDER BY MAT_TRACK_NO, FAMILY_CODE, MAT_SEQ_NO;


select REC_ID,
       '2024' as YEAR,
       SOURCE_ITEM_CAT,
       SOURCE_ITEM_SUB_CAT,
       SOURCE_ITEM_CODE,
       SOURCE_ITEM_NAME,
       SOURCE_ITEM_ENAME,
       '意见征求稿' as SOURCE,
       NCV,
       NCV_UNIT,
       C_CONTENT,
       C_CONTENT_UNIT,
       OXIDATION_RATE,
       EF,
       EF_OXIDATION,
       EF_UNIT,
       FLAG,
       REMARK,
       REC_CREATOR,
       REC_CREATE_TIME,
       REC_REVISOR,
       REC_REVISE_TIME
from T_ADS_FACT_CBAM_FACTOR_LIBRARY where YEAR = '2025'
                                      and source = '生态环境部';

select *
from T_ADS_FACT_CBAM_FACTOR_LIBRARY where YEAR = '2025'
                                      and source = '生态环境部';


select * from T_ADS_FACT_CBAM_FACTOR_LIBRARY;


select * from T_ADS_FACT_LCA_PROC_DATA
where COMPANY_CODE = 'TA'
and START_YM = '202401'
and BATCH_NUMBER = '20240120241220250107YS'
and LCA_DATA_ITEM_CAT_CODE > '05'





