CREATE OR REPLACE PROCEDURE BG00MAC102.P_ADS_LCA_BIGCLASS_DELETE_RECORD(IN V_BIGCLASS_REC_ID VARCHAR(36))
    SPECIFIC P_ADS_LCA_BIGCLASS_CALC_DELETE_RECORD
    LANGUAGE SQL
    NOT DETERMINISTIC
    EXTERNAL ACTION
    MODIFIES SQL DATA
    INHERIT SPECIAL REGISTERS
    OLD SAVEPOINT LEVEL
    DYNAMIC RESULT SETS 1
BEGIN

    DECLARE RES CURSOR WITH RETURN FOR
        SELECT V_BIGCLASS_REC_ID FROM SYSIBM.SYSDUMMY1;

    DELETE FROM BG00MAC102.T_ADS_FACT_LCA_BIGCLASS_PROC_PRODUCTION WHERE BIGCLASS_REC_ID = V_BIGCLASS_REC_ID;
    DELETE FROM BG00MAC102.T_ADS_FACT_LCA_BIGCLASS_ACTIVITY_LEVEL_IMPACT WHERE BIGCLASS_REC_ID = V_BIGCLASS_REC_ID;
    DELETE FROM BG00MAC102.T_ADS_FACT_LCA_BIGCLASS_ACTIVITY_LEVEL_DATA WHERE BIGCLASS_REC_ID = V_BIGCLASS_REC_ID;
    DELETE FROM BG00MAC102.T_ADS_FACT_LCA_BIGCLASS_INPUT_OUTPUT_MATRIX WHERE BIGCLASS_REC_ID = V_BIGCLASS_REC_ID;
    DELETE FROM BG00MAC102.T_ADS_FACT_LCA_BIGCLASS_IMPACT_RESULT WHERE BIGCLASS_REC_ID = V_BIGCLASS_REC_ID;
    DELETE FROM BG00MAC102.T_ADS_FACT_LCA_BIGCLASS_IMPACT_CONTRIBUTION WHERE BIGCLASS_REC_ID = V_BIGCLASS_REC_ID;
    DELETE FROM BG00MAC102.T_ADS_DIM_LCA_BIGCLASS_CALC_RECORD WHERE BIGCLASS_REC_ID = V_BIGCLASS_REC_ID;

    OPEN RES;

END;