create table BG00MAC102.T_ADS_FACT_LCA_PCR_ALLOCATION_FACTOR
(
    PCR                    VARCHAR(100)    not null
        constraint FK_ALLOCATION_FACTOR_PCR
            references BG00MAC102.T_ADS_DIM_LCA_PCR,
    ALLOCATION_METHOD      VARCHAR(255)    not null,
    PROC_CATEGORY          VARCHAR(255)    not null,
    PROC_CATEGORY_CNAME    VARCHAR(255),
    PRODUCT_CATEGORY       VARCHAR(255)    not null,
    PRODUCT_CATEGORY_CNAME VARCHAR(255),
    ALLOCATION_FACTOR      DECIMAL(20, 10) not null,
    PRIMARY KEY (PCR, ALLOCATION_METHOD, PROC_CATEGORY, PRODUCT_CATEGORY)
)
    distribute by hash (PCR, ALLOCATION_METHOD, PROC_CATEGORY, PRODUCT_CATEGORY);



create table BG00MAC102.T_ADS_DIM_LCA_PCR_ALLOCATION_PROCESS
(
    PCR              VARCHAR(100) not null
        constraint FK_ALLOCATION_PROCESS_PCR
            references BG00MAC102.T_ADS_DIM_LCA_PCR,
    COMPANY_CODE     VARCHAR(20)  NOT NULL,
    PROC_CATEGORY    VARCHAR(255) NOT NULL,
    PROC_KEY_BEFORE  VARCHAR(255) not null,
    PROC_CODE_BEFORE VARCHAR(255),
    PROC_NAME_BEFORE VARCHAR(255),
    PROC_KEY_AFTER   VARCHAR(255) not null,
    PROC_CODE_AFTER  VARCHAR(255),
    PROC_NAME_AFTER  VARCHAR(255),
    PRODUCT_CATEGORY VARCHAR(255) NOT NULL,
    ITEM_CAT_CODE    VARCHAR(10)  NOT NULL,
    ITEM_CODE        VARCHAR(255) NOT NULL,
    ITEM_NAME        VARCHAR(255),
    PRIMARY KEY (PCR, COMPANY_CODE, PROC_KEY_BEFORE, ITEM_CAT_CODE, ITEM_CODE)
);


CREATE TABLE BG00MAC102.T_ADS_FACT_LCA_BIGCLASS_INPUT_OUTPUT_MATRIX
(
    BIGCLASS_REC_ID VARCHAR(36)  not null
        constraint FK_BIGCLASS_INPUT_OUTPUT_MATRIX_BIGCLASS_REC_ID
            references BG00MAC102.T_ADS_DIM_LCA_BIGCLASS_CALC_RECORD,
    SOURCE_PROC_KEY VARCHAR(255) NOT NULL,
    TARGET_PROC_KEY VARCHAR(255) NOT NULL,
    UNIT_COST       DOUBLE       NOT NULL,
    IS_INVERSED     BOOLEAN      NOT NULL,
    primary key (BIGCLASS_REC_ID, SOURCE_PROC_KEY, TARGET_PROC_KEY, IS_INVERSED)
)
    distribute by hash (BIGCLASS_REC_ID, SOURCE_PROC_KEY, TARGET_PROC_KEY, IS_INVERSED);

comment on table BG00MAC102.T_ADS_FACT_LCA_BIGCLASS_INPUT_OUTPUT_MATRIX is 'LCA大类投入产出矩阵';




