DROP TABLE BG00MAC102.T_ADS_DIM_LCA_DATABASE_VERSION;

CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_DATABASE_VERSION
(
    DATABASE_VERSION VARCHAR(100) NOT NULL,
    DATABASE_NAME    VARCHAR(100) NOT NULL,
    FULL_VERSION     VARCHAR(20)  NOT NULL,
    RELEASE_TIME     VARCHAR(100),
    SOURCE           VARCHAR(100),
    DESCRIPTION      VARCHAR(100),
    IS_ACTIVE        BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (DATABASE_VERSION)
) DISTRIBUTE BY HASH (DATABASE_VERSION) ORGANIZE BY ROW;

-- CREATE UNIQUE INDEX IDX_DATABASE_VERSION ON BG00MAC102.T_ADS_DIM_LCA_DATABASE_VERSION (DATABASE_VERSION_ID, DATABASE_VERSION);

INSERT INTO BG00MAC102.T_ADS_DIM_LCA_DATABASE_VERSION (DATABASE_VERSION, DATABASE_NAME, FULL_VERSION, RELEASE_TIME,
                                                       SOURCE,
                                                       DESCRIPTION, IS_ACTIVE)
VALUES ('ecoinvent-v3.11', 'ecoinvent', '3.11', 'November 19th, 2024', 'SimaPro-v10.2',
        null, true);

INSERT INTO BG00MAC102.T_ADS_DIM_LCA_DATABASE_VERSION (DATABASE_VERSION, DATABASE_NAME, FULL_VERSION, RELEASE_TIME,
                                                       SOURCE,
                                                       DESCRIPTION, IS_ACTIVE)
VALUES ('ecoinvent-v3.8', 'ecoinvent', '3.8', 'September 21st, 2021', '易碳', null, true);

