CALL BG00MAC102.P_ADS_FACT_LCA_SUBCLASS_CALC(
        V_PCR => 'NORM',
        V_COMPANY_CODE => 'TA',
        V_START_YM => NULL,
        V_END_YM => NULL,
        V_FACTOR_YEAR => '2025',
        V_FACTOR_VERSION => 'NORM_Ecoinvent3.11',
        V_AUTO_BATCH => TRUE,
        V_BATCH_SUFFIX => NULL,
        V_MAIN_CAT_TAB_NAME => 'T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_RESULT',
        V_MAIN_CAT_BATCH_NUMBER => '20250120250120251201YS',
        V_SUBCLASS_TAB_NAME => 'T_ADS_FACT_LCA_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_DIST_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110_DIST',
        V_SUBCLASS_FILTER_CONDITION => 'AND MAT_TRACK_NO NOT IN (SELECT DISTINCT MAT_TRACK_NO FROM BG00MAC102.T_ADS_FACT_LCA_HP0001_2025_NEW_1110 WHERE UPDATE_DATE < ''202401'')'
     );

CALL BG00MAC102.P_DROP_TEMP_TABLE('BG00MAC102', 'T_ADS_TEMP_LCA_SUBCLASS_CALC');
COMMIT;

CALL BG00MAC102.P_ADS_FACT_LCA_SUBCLASS_READ_ACTI_DATA(
        V_PCR => 'NORM',
        V_COMPANY_CODE => 'TA',
        V_START_YM => NULL,
        V_END_YM => NULL,
        V_FACTOR_YEAR => '2025',
        V_FACTOR_VERSION => 'NORM_Ecoinvent3.11',
        V_AUTO_BATCH => TRUE,
        V_BATCH_SUFFIX => NULL,
        V_MAIN_CAT_TAB_NAME => 'T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_RESULT',
        V_MAIN_CAT_BATCH_NUMBER => '20250120250120251201YS',
        V_SUBCLASS_TAB_NAME => 'T_ADS_FACT_LCA_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_DIST_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110_DIST'
     );

CALL BG00MAC102.P_ADS_FACT_LCA_SUBCLASS_READ_ENERGY_RESULT(
        V_PCR => 'NORM',
        V_COMPANY_CODE => 'TA',
        V_START_YM => NULL,
        V_END_YM => NULL,
        V_FACTOR_YEAR => '2025',
        V_FACTOR_VERSION => 'NORM_Ecoinvent3.11',
        V_AUTO_BATCH => TRUE,
        V_BATCH_SUFFIX => NULL,
        V_MAIN_CAT_TAB_NAME => 'T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_RESULT',
        V_MAIN_CAT_BATCH_NUMBER => '20250120250120251201YS',
        V_SUBCLASS_TAB_NAME => 'T_ADS_FACT_LCA_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_MONTH_RESULT_TA_HP0001',
        V_SUBCLASS_RESULT_DIST_TAB_NAME => NULL
     );

CALL BG00MAC102.P_ADS_FACT_LCA_SUBCLASS_READ_FACTOR(
        V_PCR => 'NORM',
        V_COMPANY_CODE => 'TA',
        V_START_YM => NULL,
        V_END_YM => NULL,
        V_FACTOR_YEAR => '2025',
        V_FACTOR_VERSION => 'NORM_Ecoinvent3.11',
        V_AUTO_BATCH => TRUE,
        V_BATCH_SUFFIX => NULL,
        V_MAIN_CAT_TAB_NAME => 'T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_RESULT',
        V_MAIN_CAT_BATCH_NUMBER => '20250120250120251201YS',
        V_SUBCLASS_TAB_NAME => 'T_ADS_FACT_LCA_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_DIST_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110_DIST'
     );

CALL BG00MAC102.P_ADS_FACT_LCA_SUBCLASS_JOIN_DIST(
        V_PCR => 'NORM',
        V_COMPANY_CODE => 'TA',
        V_START_YM => NULL,
        V_END_YM => NULL,
        V_FACTOR_YEAR => '2025',
        V_FACTOR_VERSION => 'NORM_Ecoinvent3.11',
        V_AUTO_BATCH => TRUE,
        V_BATCH_SUFFIX => NULL,
        V_MAIN_CAT_TAB_NAME => 'T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_RESULT',
        V_MAIN_CAT_BATCH_NUMBER => '20250120250120251201YS',
        V_SUBCLASS_TAB_NAME => 'T_ADS_FACT_LCA_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_DIST_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110_DIST'
     );


CALL BG00MAC102.P_ADS_FACT_LCA_SUBCLASS_RECURSION(
        V_PCR => 'NORM',
        V_COMPANY_CODE => 'TA',
        V_START_YM => NULL,
        V_END_YM => NULL,
        V_FACTOR_YEAR => '2025',
        V_FACTOR_VERSION => 'NORM_Ecoinvent3.11',
        V_AUTO_BATCH => TRUE,
        V_BATCH_SUFFIX => NULL,
        V_MAIN_CAT_TAB_NAME => 'T_ADS_FACT_LCA_MAIN_CAT_EPD_NORM_RESULT',
        V_MAIN_CAT_BATCH_NUMBER => '20250120250120251201YS',
        V_SUBCLASS_TAB_NAME => 'T_ADS_FACT_LCA_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110',
        V_SUBCLASS_RESULT_DIST_TAB_NAME => 'T_ADS_FACT_LCA_SUBCLASS_EPD_NORM_GWP_RESULT_HP0001_2025_NEW_1110_DIST'
     );






