create table BG00MAC102.T_ADS_FACT_LCA_EPD_LCI_ELEMENT_NORM_CONS_MAP
(
    REC_ID                VARCHAR(64),
    NORM_LCI_ELEMENT_ID   VARCHAR(64),
    NORM_LCI_ELEMENT_NAME VARCHAR(256),
    CONS_LCI_ELEMENT_ID   VARCHAR(64),
    CONS_LCI_ELEMENT_NAME VARCHAR(256)
)
    distribute by hash (REC_ID);

comment on table BG00MAC102.T_ADS_FACT_LCA_EPD_LCI_ELEMENT_NORM_CONS_MAP is '普通和建筑用钢EPD因子清单对照表';
