create table BG00MAC102.T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION
(
    REC_ID            VARCHAR(32) default NULL,
    VERSION           VARCHAR(100),
    LCI_ELEMENT_CODE  VARCHAR(32),
    LCI_ELEMENT_NAME  VARCHAR(500),
    LCI_ELEMENT_CNAME VARCHAR(500),
    LCI_ELEMENT_UNIT  VARCHAR(32)
)
    distribute by hash (REC_ID);

comment on table BG00MAC102.T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION is '建筑用钢EPD因子库版本代码名称';

comment on column BG00MAC102.T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION.REC_ID is '记录识别码';

comment on column BG00MAC102.T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION.VERSION is '因子库版本';

comment on column BG00MAC102.T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION.LCI_ELEMENT_CODE is '因子代码';

comment on column BG00MAC102.T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION.LCI_ELEMENT_NAME is '因子名称';

comment on column BG00MAC102.T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION.LCI_ELEMENT_CNAME is '因子中文名称';

comment on column BG00MAC102.T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION.LCI_ELEMENT_UNIT is '因子单位';

