select *
from T_ADS_FACT_LCA_PROC_DATA_0002_DT
where COMPANY_CODE = 'ZG';

-- and BATCH_NUMBER = '20240120241220250915YS'
-- and LCA_PROC_CODE = 'LG04'
-- and LCA_DATA_ITEM_CODE = '58280';

select *
from T_ADS_WH_LCA_FACTOR_LIBRARY_LCI_CONS
where VERSION like 'EF%'
  and LCI_ELEMENT_CODE = 'GWP-total'
order by NAME;


insert into T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION (VERSION, LCI_ELEMENT_CODE, LCI_ELEMENT_NAME,
                                                  LCI_ELEMENT_CNAME, LCI_ELEMENT_UNIT)
select 'EN15804_Ecoinvent3.11', LCI_ELEMENT_CODE, LCI_ELEMENT_NAME, LCI_ELEMENT_CNAME, LCI_ELEMENT_UNIT
from T_ADS_WH_LCA_EPD_CONS_FACTOR_VERSION
where VERSION = 'EF3.1_Ecoinvent3.11';


select * from T_ADS_FACT_LCA_PROC_DATA_0002_DT
where COMPANY_CODE = 'ZG';

