DROP TABLE BG00MAC102.T_ADS_DIM_LCA_DATASET_ACTIVITY;

CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_DATASET_ACTIVITY
(
    ACTIVITY_ID           VARCHAR(36)  NOT NULL PRIMARY KEY,
    DATABASE_VERSION      VARCHAR(100) NOT NULL,
    SYSTEM_MODEL          VARCHAR(255) NOT NULL,
    ACTIVITY_NAME         VARCHAR(255) NOT NULL,
    GEOGRAPHY_ID          VARCHAR(36),
    TIME_PERIOD           VARCHAR(20),
    SPECIAL_ACTIVITY_TYPE VARCHAR(255),
    SECTOR                VARCHAR(255),
    ISIC_SECTION          VARCHAR(255),
    ISIC_CLASSIFICATION   VARCHAR(255),
    CONSTRAINT FK_DATASET_ACTIVITY_DATABASE_VERSION
        FOREIGN KEY (DATABASE_VERSION) REFERENCES BG00MAC102.T_ADS_DIM_LCA_DATABASE_VERSION (DATABASE_VERSION),
    CONSTRAINT FK_DATASET_ACTIVITY_SYSTEM_MODEL
        FOREIGN KEY (SYSTEM_MODEL) REFERENCES BG00MAC102.T_ADS_DIM_LCA_SYSTEM_MODEL (SYSTEM_MODEL),
    CONSTRAINT FK_DATASET_ACTIVITY_GEOGRAPHY_SHORTNAME
        FOREIGN KEY (GEOGRAPHY_ID) REFERENCES BG00MAC102.T_ADS_DIM_LCA_GEOGRAPHY (GEOGRAPHY_ID)
) DISTRIBUTE BY HASH (ACTIVITY_ID);

truncate BG00MAC102.T_ADS_DIM_LCA_DATASET_ACTIVITY immediate;

DROP TABLE BG00MAC102.T_ADS_DIM_LCA_DATASET_PRODUCT;

CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_DATASET_PRODUCT
(
    PRODUCT_ID            VARCHAR(36)  NOT NULL PRIMARY KEY,
    PRODUCT_NAME          VARCHAR(255) NOT NULL,
    CPC_CLASSIFICATION    VARCHAR(255),
    HS2017_CLASSIFICATION VARCHAR(255),
    UNIT_NAME             VARCHAR(255),
    PRODUCT_INFORMATION   VARCHAR(5000),
    CAS_NUMBER            VARCHAR(255),
    CUTOFF_CLASSIFICATION VARCHAR(255),
    APOS_CLASSIFICATION   VARCHAR(255)
) DISTRIBUTE BY HASH (PRODUCT_ID);


DROP TABLE BG00MAC102.T_ADS_DIM_LCA_DATASET;

CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_DATASET
(
    DATASET_ID       VARCHAR(73)  NOT NULL PRIMARY KEY,
    DATABASE_VERSION VARCHAR(100) NOT NULL,
    SYSTEM_MODEL     VARCHAR(255) NOT NULL,
    ACTIVITY_ID      VARCHAR(36)  NOT NULL,
    PRODUCT_ID       VARCHAR(36)  NOT NULL,
    DATASET_URL      VARCHAR(1000),
    CONSTRAINT FK_DATASET_DATABASE_VERSION
        FOREIGN KEY (DATABASE_VERSION) REFERENCES BG00MAC102.T_ADS_DIM_LCA_DATABASE_VERSION (DATABASE_VERSION),
    CONSTRAINT FK_DATASET_SYSTEM_MODEL
        FOREIGN KEY (SYSTEM_MODEL) REFERENCES BG00MAC102.T_ADS_DIM_LCA_SYSTEM_MODEL (SYSTEM_MODEL),
    CONSTRAINT FK_DATASET_ACTIVITY_ID
        FOREIGN KEY (ACTIVITY_ID) REFERENCES BG00MAC102.T_ADS_DIM_LCA_DATASET_ACTIVITY (ACTIVITY_ID),
    CONSTRAINT FK_DATASET_PRODUCT_ID
        FOREIGN KEY (PRODUCT_ID) REFERENCES BG00MAC102.T_ADS_DIM_LCA_DATASET_PRODUCT (PRODUCT_ID)
) DISTRIBUTE BY HASH (DATASET_ID);


CREATE VIEW BG00MAC102.V_ADS_LCA_DATASET_ACTIVITY_OVERVIEW AS
SELECT ROW_NUMBER() OVER () AS ROW_ID,
       DS.DATASET_ID,
       DS.DATABASE_VERSION,
       DS.SYSTEM_MODEL,
       DS.DATASET_URL,
       AC.ACTIVITY_ID,
       AC.ACTIVITY_NAME,
       GEO.GEOGRAPHY_ID,
       GEO.GEOGRAPHY_SHORTNAME,
       GEO.GEOGRAPHY_NAME,
       AC.TIME_PERIOD,
       AC.SPECIAL_ACTIVITY_TYPE,
       AC.SECTOR,
       AC.ISIC_SECTION,
       AC.ISIC_CLASSIFICATION,
       PD.PRODUCT_ID,
       PD.PRODUCT_NAME,
       PD.CPC_CLASSIFICATION,
       PD.HS2017_CLASSIFICATION,
       PD.UNIT_NAME,
       PD.PRODUCT_INFORMATION,
       PD.CAS_NUMBER,
       PD.CUTOFF_CLASSIFICATION,
       PD.APOS_CLASSIFICATION
FROM BG00MAC102.T_ADS_DIM_LCA_DATASET DS
         JOIN BG00MAC102.T_ADS_DIM_LCA_DATASET_ACTIVITY AC
              ON DS.ACTIVITY_ID = AC.ACTIVITY_ID
         JOIN BG00MAC102.T_ADS_DIM_LCA_DATASET_PRODUCT PD
              ON DS.PRODUCT_ID = PD.PRODUCT_ID
         JOIN BG00MAC102.T_ADS_DIM_LCA_GEOGRAPHY GEO
              ON AC.GEOGRAPHY_ID = GEO.GEOGRAPHY_ID;


SELECT *
FROM BG00MAC102.V_ADS_LCA_DATASET_ACTIVITY_OVERVIEW
ORDER BY DATABASE_VERSION, SYSTEM_MODEL, GEOGRAPHY_SHORTNAME, ISIC_SECTION, SECTOR, ACTIVITY_NAME, CPC_CLASSIFICATION,
         PRODUCT_NAME;


WITH MATCHED AS (SELECT *, COUNT(*) OVER ( PARTITION BY NAME) AS COUNT_ROW
                 FROM (SELECT DISTINCT NAME, BACKGROUND
                       FROM BG00MAC102.T_ADS_WH_LCA_BACKGROUND_FACTOR_LIBRARY
                       WHERE VERSION = 'NORM_Ecoinvent3.11'
                         AND FLAG IN ('MAT', 'TRANSPORT')) A
                          LEFT JOIN (SELECT DISTINCT *,
                                                     '%{' || GEOGRAPHY_SHORTNAME || '}| ' || ACTIVITY_NAME ||
                                                     ' | Cut-off, S' AS BACKGROUND_PATTERN
                                     FROM BG00MAC102.V_ADS_LCA_DATASET_ACTIVITY_OVERVIEW
                                     WHERE DATABASE_VERSION = 'ecoinvent-v3.11'
                                       AND SYSTEM_MODEL = 'cutoff') B ON A.BACKGROUND like B.BACKGROUND_PATTERN)
SELECT DISTINCT *
FROM MATCHED
WHERE COUNT_ROW = 1
ORDER BY NAME
;




select * from T_ADS_DIM_LCA_PCR_INDICATOR PI
where exists(select * from T_ADS_DIM_LCA_IMPACT_INDICATOR II
                      where PI.REFERENCE_IMPACT_INDICATOR_ID = II.IMPACT_INDICATOR_ID
                      and II.USED_IN_EN15804);



