create table BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC
(
    SOURCE_DOC_ID   VARCHAR(36)                  not null
        primary key,
    DATE_OF_ISSUE   DATE,
    VALID_FROM      VARCHAR(6),
    VALID_UNTIL     VARCHAR(6),
    SOURCE_CODE     VARCHAR(20),
    SOURCE_NAME     VARCHAR(255),
    SOURCE_DOC_NAME VARCHAR(255),
    SOURCE_DOC_CODE VARCHAR(255),
    SOURCE_DOC_URL  VARCHAR(1000),
    IS_VALID        BOOLEAN      default TRUE,
    IS_MIGRATED     BOOLEAN      default FALSE,
    TIME_FACTOR     VARCHAR(255),
    GEO_DES         VARCHAR(2500),
    GEO_FACTOR      VARCHAR(255),
    PRE_DES         VARCHAR(2500),
    PRE_FACTOR      VARCHAR(255),
    COM_DES         VARCHAR(2500),
    COM_FACTOR      VARCHAR(255),
    REC_CREATOR     VARCHAR(255) default 'admin' not null,
    REC_CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP,
    REC_REVISOR     VARCHAR(255),
    REC_REVISE_TIME TIMESTAMP(6)
)
    distribute by hash (SOURCE_DOC_ID);

comment on table BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC is '排放因子库来源文件信息';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.SOURCE_DOC_ID is '来源文件ID';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.DATE_OF_ISSUE is '签发日期';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.VALID_FROM is '起始生效时间';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.VALID_UNTIL is '结束生效时间';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.SOURCE_CODE is '来源代码';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.SOURCE_NAME is '来源名称';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.SOURCE_DOC_NAME is '来源文件名称';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.SOURCE_DOC_CODE is '来源文件代码';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.SOURCE_DOC_URL is '来源文件URL';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.IS_VALID is '是否生效';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.IS_MIGRATED is '是否从原数据库迁移';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.TIME_FACTOR is '时间因子';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.GEO_DES is '地理描述';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.GEO_FACTOR is '地理因子';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.PRE_DES is '精度描述';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.PRE_FACTOR is '精度因子';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.COM_DES is '完整性描述';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.COM_FACTOR is '完整性因子';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.REC_CREATOR is '记录创建人';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.REC_CREATE_TIME is '记录创建时间';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.REC_REVISOR is '记录修改人';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC.REC_REVISE_TIME is '记录修改时间';

