DROP TABLE BG00MAC102.T_ADS_DIM_LCA_GEOGRAPHY;

CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_GEOGRAPHY
(
    GEOGRAPHY_ID                    VARCHAR(36)  NOT NULL PRIMARY KEY,
    GEOGRAPHY_NAME                  VARCHAR(255) NOT NULL,
    GEOGRAPHY_SHORTNAME             VARCHAR(255) NOT NULL,
    LATITUDE                        DECIMAL(20, 10),
    LONGITUDE                       DECIMAL(20, 10),
    GEOGRAPHY_CLASSIFICATION        VARCHAR(255),
    CONTAINED_OVERLAPPING_GEOGRAPHY VARCHAR(5000)
);

drop TABLE BG00MAC102.T_ADS_DIM_LCA_GEOGRAPHY;
