DROP TABLE BG00MAC102.T_ADS_DIM_LCA_IMPACT_METHOD;

CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_IMPACT_METHOD
(
    IMPACT_METHOD_ID                   VARCHAR(36)  NOT NULL PRIMARY KEY,
    IMPACT_METHOD_NAME                 VARCHAR(255) NOT NULL,
    IMPACT_METHOD_VERSION              VARCHAR(255),
    IS_CURRENT                         BOOLEAN DEFAULT TRUE,
    ECOINVENT_DOCUMENTATION            VARCHAR(255),
    FURTHER_DOCUMENTATION              VARCHAR(255),
    CHARACTERIZATION_FACTOR_SOURCE_URL VARCHAR(255)
) DISTRIBUTE BY HASH (IMPACT_METHOD_ID);


CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_IMPACT_CATEGORY
(
    IMPACT_CATEGORY_ID             VARCHAR(36)  NOT NULL PRIMARY KEY,
    IMPACT_METHOD_ID               VARCHAR(36)  NOT NULL,
    IMPACT_CATEGORY_NAME           VARCHAR(255) NOT NULL,
    IMPACT_CATEGORY_NAME_IN_METHOD VARCHAR(255),
    CONSTRAINT FK_CAT_METHOD
        FOREIGN KEY (IMPACT_METHOD_ID) REFERENCES BG00MAC102.T_ADS_DIM_LCA_IMPACT_METHOD (IMPACT_METHOD_ID)
) DISTRIBUTE BY HASH (IMPACT_CATEGORY_ID);

-- CREATE TABLE Unit
-- (
--     unitId   INT PRIMARY KEY,
--     unitName VARCHAR(255) NOT NULL UNIQUE
-- );

CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_IMPACT_INDICATOR
(
    IMPACT_INDICATOR_ID             VARCHAR(36)  NOT NULL PRIMARY KEY,
    IMPACT_CATEGORY_ID              VARCHAR(36)  NOT NULL,
    IMPACT_INDICATOR_NAME           VARCHAR(255) NOT NULL,
    IMPACT_INDICATOR_CNAME          VARCHAR(255),
    UNIT_NAME                       VARCHAR(255) NOT NULL,
    IMPACT_INDICATOR_NAME_IN_METHOD VARCHAR(255),
    UNIT_NAME_IN_METHOD             VARCHAR(255),
    RESOURCES_EMISSIONS_TOTAL       VARCHAR(255),
    MAIN_IMPACT_DAMAGE_CATEGORY     VARCHAR(255),
    INVENTORY_MIDPOINT_ENDPOINT_AOP VARCHAR(255),
    AREA_OF_PROTECTION              VARCHAR(255),
    USED_IN_EN15804                 BOOLEAN DEFAULT FALSE,
    IS_GWP_TOTAL                    BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_IND_CAT
        FOREIGN KEY (IMPACT_CATEGORY_ID) REFERENCES BG00MAC102.T_ADS_DIM_LCA_IMPACT_CATEGORY (IMPACT_CATEGORY_ID)
) DISTRIBUTE BY HASH (IMPACT_INDICATOR_ID);


DROP VIEW BG00MAC102.V_ADS_LCA_IMPACT_INDICATOR;
CREATE VIEW BG00MAC102.V_ADS_LCA_IMPACT_INDICATOR AS
SELECT ROW_NUMBER() OVER () AS ROW_ID,
       IM.IMPACT_METHOD_ID,
       IM.IMPACT_METHOD_NAME,
       IM.IMPACT_METHOD_VERSION,

       IC.IMPACT_CATEGORY_ID,
       IC.IMPACT_CATEGORY_NAME,

       II.IMPACT_INDICATOR_ID,
       II.IMPACT_INDICATOR_NAME,
       II.IMPACT_INDICATOR_CNAME,
       II.UNIT_NAME,
       IC.IMPACT_CATEGORY_NAME_IN_METHOD,
       II.IMPACT_INDICATOR_NAME_IN_METHOD,
       II.UNIT_NAME_IN_METHOD,
       II.RESOURCES_EMISSIONS_TOTAL,
       II.MAIN_IMPACT_DAMAGE_CATEGORY,
       II.INVENTORY_MIDPOINT_ENDPOINT_AOP,
       II.AREA_OF_PROTECTION,
       II.USED_IN_EN15804,
       II.IS_GWP_TOTAL,
       IM.IS_CURRENT
FROM BG00MAC102.T_ADS_DIM_LCA_IMPACT_INDICATOR II
         JOIN BG00MAC102.T_ADS_DIM_LCA_IMPACT_CATEGORY IC
              ON II.IMPACT_CATEGORY_ID = IC.IMPACT_CATEGORY_ID
         JOIN BG00MAC102.T_ADS_DIM_LCA_IMPACT_METHOD IM
              ON IC.IMPACT_METHOD_ID = IM.IMPACT_METHOD_ID;


SELECT *
FROM BG00MAC102.V_ADS_LCA_IMPACT_INDICATOR
ORDER BY IMPACT_METHOD_NAME, IMPACT_CATEGORY_NAME, IMPACT_INDICATOR_NAME;
-- CREATE TABLE FactImpactAmount
-- (
--     impactIndicatorId VARCHAR(36) PRIMARY KEY,
--     amount            DOUBLE PRECISION NOT NULL,
--     CONSTRAINT fk_fact_indicator
--         FOREIGN KEY (impactIndicatorId) REFERENCES ImpactIndicator (impactIndicatorId)
-- );


UPDATE BG00MAC102.T_ADS_DIM_LCA_IMPACT_INDICATOR f
SET IS_GWP_TOTAL = TRUE
WHERE IMPACT_INDICATOR_ID IN ('0e8ded58-82fd-491c-a5d3-1c2e100cb843',
                              'c621b8a6-0fdb-4c90-bf13-3215df559b3c',
                              'eabe9472-7546-434a-888f-2efdcf9cac46',
                              '6d85469e-cb4b-430d-8dbf-d83a3ce07c22',
                              'c953f95b-9d3b-4574-aa1c-6fd8498540e7',
                              '07e6ca75-ea62-4fad-afa1-e11b03a2071f',
                              '87d85ddc-eeb7-4c46-bdb2-4ad5fdb0e6b1',
                              '818618c9-dd6b-42e7-a559-02b59779ad73',
                              '9d92c679-54c2-4055-a447-3f128dfbf02f',
                              'd7964007-0507-441b-92d1-c24885c76bcb');











