DROP TABLE BG00MAC102.T_ADS_DIM_LCA_PCR_INDICATOR;

CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_PCR_INDICATOR
(
    PCR_INDICATOR_ID              VARCHAR(36)  NOT NULL PRIMARY KEY,
    PCR                           VARCHAR(100) NOT NULL,
    INDICATOR_CODE                VARCHAR(255) NOT NULL,
    INDICATOR_NAME_IN_PCR         VARCHAR(255),
    INDICATOR_CNAME_IN_PCR        VARCHAR(255),
    INDICATOR_UNIT_IN_PCR         VARCHAR(255),
    REFERENCE_IMPACT_INDICATOR_ID VARCHAR(36),
    CONSTRAINT FK_UNIT_PROCESS_ID
        FOREIGN KEY (PCR) REFERENCES BG00MAC102.T_ADS_DIM_LCA_PCR (PCR),
    CONSTRAINT FK_IMPACT_INDICATOR_ID
        FOREIGN KEY (REFERENCE_IMPACT_INDICATOR_ID) REFERENCES BG00MAC102.T_ADS_DIM_LCA_IMPACT_INDICATOR (IMPACT_INDICATOR_ID)
) DISTRIBUTE BY HASH (PCR_INDICATOR_ID) ORGANIZE BY ROW;


TRUNCATE T_ADS_DIM_LCA_PCR_INDICATOR IMMEDIATE;

SELECT IMPACT_INDICATOR_ID,
       IMPACT_METHOD_ID,
       IMPACT_METHOD_NAME,
       IMPACT_METHOD_VERSION,
       IMPACT_CATEGORY_NAME,
       IMPACT_INDICATOR_NAME,
       UNIT_NAME,
       USED_IN_EN15804
FROM V_ADS_LCA_IMPACT_INDICATOR
ORDER BY IMPACT_METHOD_NAME,
         IMPACT_METHOD_VERSION,
         IMPACT_CATEGORY_NAME,
         IMPACT_INDICATOR_NAME,
         UNIT_NAME,
         USED_IN_EN15804;

select distinct *
from T_ADS_WH_LCA_FACTOR_LIBRARY_LCI_CONS
where VERSION = 'EN15804_Ecoinvent3.11'
  and LCI_ELEMENT_CODE = 'GWP-total';


SELECT PI.PCR_INDICATOR_ID,
       PI.PCR,
       P.PCR_NAME,
       P.PCR_CNAME,
       INDICATOR_CODE,
       INDICATOR_NAME_IN_PCR,
       INDICATOR_CNAME_IN_PCR,
       INDICATOR_UNIT_IN_PCR,
       REFERENCE_IMPACT_INDICATOR_ID,
       PCR_INDICATOR_ID,
       II.IMPACT_METHOD_NAME,
       II.IMPACT_METHOD_VERSION,
       II.IMPACT_CATEGORY_NAME,
       II.IMPACT_INDICATOR_NAME,
       II.IMPACT_INDICATOR_CNAME,
       II.UNIT_NAME,
       II.IMPACT_CATEGORY_NAME_IN_METHOD,
       II.IMPACT_INDICATOR_NAME_IN_METHOD,
       II.UNIT_NAME_IN_METHOD,
       II.RESOURCES_EMISSIONS_TOTAL,
       II.MAIN_IMPACT_DAMAGE_CATEGORY,
       II.INVENTORY_MIDPOINT_ENDPOINT_AOP,
       II.AREA_OF_PROTECTION,
       II.USED_IN_EN15804,
       II.IS_GWP_TOTAL,
       II.IS_CURRENT
FROM T_ADS_DIM_LCA_PCR_INDICATOR PI
         LEFT JOIN T_ADS_DIM_LCA_PCR P
                   ON PI.PCR = P.PCR
         LEFT JOIN V_ADS_LCA_IMPACT_INDICATOR II
                   ON PI.REFERENCE_IMPACT_INDICATOR_ID = II.IMPACT_INDICATOR_ID
ORDER BY PCR, INDICATOR_CODE;


SELECT *
FROM T_ADS_DIM_LCA_IMPACT_INDICATOR II
WHERE EXISTS(SELECT 1
             FROM T_ADS_DIM_LCA_IMPACT_CATEGORY IC
                      JOIN T_ADS_DIM_LCA_IMPACT_METHOD IM ON IC.IMPACT_METHOD_ID = IM.IMPACT_METHOD_ID
             WHERE IC.IMPACT_CATEGORY_ID = II.IMPACT_CATEGORY_ID
               AND IC.IMPACT_CATEGORY_NAME = 'ozone depletion no LT'
               AND IM.IMPACT_METHOD_NAME = 'Inventory results and indicators')
AND EXISTS()

