SELECT DISTINCT NAME, BACKGROUND, UNIT
FROM BG00MAC102.T_ADS_WH_LCA_BACKGROUND_FACTOR_LIBRARY
WHERE VERSION = 'NORM_Ecoinvent3.11'
  AND FLAG IN ('MAT', 'TRANSPORT');

SELECT DISTINCT *,
                PRODUCT_NAME || ' {' || GEOGRAPHY_SHORTNAME || '}| ' || ACTIVITY_NAME ||
                ' | Cut-off, S' AS BACKGROUND
FROM BG00MAC102.V_ADS_LCA_DATASET_ACTIVITY_OVERVIEW
WHERE DATABASE_VERSION = 'ecoinvent-v3.11'
  AND SYSTEM_MODEL = 'cutoff';


DROP TABLE BG00MAC102.T_ADS_DIM_LCA_UNIT_PROCESS;

CREATE TABLE BG00MAC102.T_ADS_DIM_LCA_UNIT_PROCESS
(
    UNIT_PROCESS_ID      VARCHAR(36)  NOT NULL PRIMARY KEY,
    UNIT_PROCESS_NAME    VARCHAR(255) NOT NULL,
    PCR                  VARCHAR(100) NOT NULL,
    SOURCE               VARCHAR(255),
    CATEGORY             VARCHAR(255) NOT NULL DEFAULT 'UPSTREAM',
    BACKGROUND_INFO      VARCHAR(255),
    UNIT_NAME            VARCHAR(255),
    REFERENCE_DATASET_ID VARCHAR(73),
    CONVERSION_FACTOR    DECIMAL(20, 10)       DEFAULT 1,
    IS_DIESEL            BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT FK_UNIT_PROCESS_PCR
        FOREIGN KEY (PCR) REFERENCES BG00MAC102.T_ADS_DIM_LCA_PCR (PCR),
    CONSTRAINT FK_UNIT_PROCESS_DATASET_ID
        FOREIGN KEY (REFERENCE_DATASET_ID) REFERENCES BG00MAC102.T_ADS_DIM_LCA_DATASET (DATASET_ID)
) DISTRIBUTE BY HASH (UNIT_PROCESS_ID);



DROP TABLE BG00MAC102.T_ADS_FACT_LCA_UNIT_PROCESS_IMPACT;

CREATE TABLE BG00MAC102.T_ADS_FACT_LCA_UNIT_PROCESS_IMPACT
(
    UNIT_PROCESS_ID     VARCHAR(36) NOT NULL,
    IMPACT_INDICATOR_ID VARCHAR(36) NOT NULL,
    AMOUNT              DECIMAL(30, 16),
    PRIMARY KEY (UNIT_PROCESS_ID, IMPACT_INDICATOR_ID),
    CONSTRAINT FK_UNIT_PROCESS_ID
        FOREIGN KEY (UNIT_PROCESS_ID) REFERENCES BG00MAC102.T_ADS_DIM_LCA_UNIT_PROCESS (UNIT_PROCESS_ID),
    CONSTRAINT FK_IMPACT_INDICATOR_ID
        FOREIGN KEY (IMPACT_INDICATOR_ID) REFERENCES BG00MAC102.T_ADS_DIM_LCA_IMPACT_INDICATOR (IMPACT_INDICATOR_ID)
) DISTRIBUTE BY HASH (UNIT_PROCESS_ID, IMPACT_INDICATOR_ID);


SELECT *
FROM T_ADS_DIM_LCA_PCR_INDICATOR PI
WHERE PCR = 'BASIC'
  AND EXISTS(SELECT *
             FROM T_ADS_WH_LCA_EPD_NORM_FACTOR_VERSION FV
             WHERE VERSION = 'NORM_Ecoinvent3.11'
               AND FV.LCI_ELEMENT_CODE = PI.INDICATOR_CODE);


-- INSERT INTO T_ADS_FACT_LCA_UNIT_PROCESS_IMPACT (UNIT_PROCESS_ID, IMPACT_INDICATOR_ID, AMOUNT)
SELECT DISTINCT UNIT_PROCESS_ID, REFERENCE_IMPACT_INDICATOR_ID, LCI_ELEMENT_VALUE AS AMOUNT
FROM (SELECT *
      FROM T_ADS_DIM_LCA_UNIT_PROCESS
      WHERE PCR = 'BASIC') UP
         LEFT JOIN (SELECT DISTINCT *
                    FROM T_ADS_WH_LCA_BACKGROUND_FACTOR_LIBRARY
                    WHERE VERSION = 'NORM_Ecoinvent3.11'
                      AND FLAG in ('MAT', 'TRANSPORT')) BF ON UP.UNIT_PROCESS_NAME = BF.NAME
         LEFT JOIN (SELECT *
                    FROM T_ADS_DIM_LCA_PCR_INDICATOR
                    WHERE PCR = 'BASIC') PI ON BF.LCI_ELEMENT_CODE = PI.INDICATOR_CODE
;


SELECT *
FROM T_ADS_FACT_LCA_UNIT_PROCESS_IMPACT UI
WHERE EXISTS(SELECT 1
             FROM T_ADS_DIM_LCA_PCR_INDICATOR PI
             WHERE UI.IMPACT_INDICATOR_ID = PI.REFERENCE_IMPACT_INDICATOR_ID
               AND PI.PCR = 'BASIC'
               AND PI.INDICATOR_CODE = 'GWP-total')
;

SELECT *
FROM T_ADS_DIM_LCA_PCR_INDICATOR;




