create table BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR
(
    EMISSION_FACTOR_ID VARCHAR(36)  not null
        constraint FK_EMISSION_FACTOR_ID
            references BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY,
    DQR_CATEGORY       VARCHAR(255) not null
        constraint FK_DQR_CATEGORY
            references BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY,
    DQR_DESCRIPTION    VARCHAR(1000),
    DQR_VALUE          DECIMAL(20, 10),
    REC_CREATOR        VARCHAR(255) default 'admin',
    REC_CREATE_TIME    TIMESTAMP(6) default CURRENT TIMESTAMP,
    REC_REVISOR        VARCHAR(255),
    REC_REVISE_TIME    TIMESTAMP(6),
    primary key (EMISSION_FACTOR_ID, DQR_CATEGORY)
)
    distribute by hash (EMISSION_FACTOR_ID, DQR_CATEGORY);

comment on table BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR is '排放因子数据质量评分';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR.EMISSION_FACTOR_ID is '排放因子ID';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR.DQR_CATEGORY is '数据质量评分分类';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR.DQR_DESCRIPTION is '数据质量评分描述';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR.DQR_VALUE is '数据质量评分';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR.REC_CREATOR is '记录创建人';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR.REC_CREATE_TIME is '记录创建时间';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR.REC_REVISOR is '记录修改人';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_DQR.REC_REVISE_TIME is '记录修改时间';

select A.PCR,
       A.PCR_CNAME,
       B.INDICATOR_CODE,
       C.IMPACT_METHOD_NAME,
       C.IMPACT_CATEGORY_NAME,
       C.IMPACT_INDICATOR_NAME,
       UNIT_NAME,
       MAIN_IMPACT_DAMAGE_CATEGORY,
       INVENTORY_MIDPOINT_ENDPOINT_AOP
from T_ADS_DIM_LCA_PCR A
         JOIN T_ADS_DIM_LCA_PCR_INDICATOR B
              ON A.PCR = B.PCR
         JOIN V_ADS_LCA_IMPACT_INDICATOR C ON B.REFERENCE_IMPACT_INDICATOR_ID = C.IMPACT_INDICATOR_ID
ORDER BY A.PCR, C.IMPACT_METHOD_NAME, C.IMPACT_CATEGORY_NAME;
