create table BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY
(
    DQR_CATEGORY       VARCHAR(255) not null primary key,
    DQR_CATEGORY_FLAG  VARCHAR(100) not null,
    DQR_CATEGORY_CNAME VARCHAR(255),
    REC_CREATOR        VARCHAR(255) default 'admin',
    REC_CREATE_TIME    TIMESTAMP(6) default CURRENT TIMESTAMP,
    REC_REVISOR        VARCHAR(255),
    REC_REVISE_TIME    TIMESTAMP(6)
)
    distribute by hash (DQR_CATEGORY);

comment on table BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY is '排放因子数据质量评分分类';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY.DQR_CATEGORY is '数据质量评分分类';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY.DQR_CATEGORY_FLAG is '数据质量评分分类标签';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY.DQR_CATEGORY_CNAME is '数据质量评分分类中文名';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY.REC_CREATOR is '记录创建人';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY.REC_CREATE_TIME is '记录创建时间';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY.REC_REVISOR is '记录修改人';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_DQR_CATEGORY.REC_REVISE_TIME is '记录修改时间';
