create table BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY
(
    SOURCE_ITEM_CAT_ID        VARCHAR(36) not null
        primary key,
    SOURCE_DOC_ID             VARCHAR(36) not null
        constraint FK_SOURCE_DOC_ID
            references BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC,
    SOURCE_ITEM_MAIN_CAT_CODE VARCHAR(20),
    SOURCE_ITEM_MAIN_CAT_NAME VARCHAR(255),
    SOURCE_ITEM_SUB_CAT_CODE  VARCHAR(20),
    SOURCE_ITEM_SUB_CAT_NAME  VARCHAR(255),
    IS_PRODUCTION             BOOLEAN,
    REC_CREATOR               VARCHAR(255) default 'admin',
    REC_CREATE_TIME           TIMESTAMP(6) default CURRENT TIMESTAMP,
    REC_REVISOR               VARCHAR(255),
    REC_REVISE_TIME           TIMESTAMP(6)
)
    distribute by hash (SOURCE_ITEM_CAT_ID);

comment on table BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY is '排放因子分类';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.SOURCE_ITEM_CAT_ID is '排放因子分类ID';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.SOURCE_DOC_ID is '来源文件ID';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.SOURCE_ITEM_MAIN_CAT_CODE is '主分类代码';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.SOURCE_ITEM_MAIN_CAT_NAME is '主分类名称';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.SOURCE_ITEM_SUB_CAT_CODE is '子分类代码';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.SOURCE_ITEM_SUB_CAT_NAME is '子分类名称';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.IS_PRODUCTION is '是/否为生产过程/上游';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.REC_CREATOR is '记录创建人';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.REC_CREATE_TIME is '记录创建时间';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.REC_REVISOR is '记录修改人';

comment on column BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY.REC_REVISE_TIME is '记录修改时间';
