create table BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY
(
    EMISSION_FACTOR_ID      VARCHAR(36) not null
        primary key,
    EMISSION_FACTOR_CODE    VARCHAR(255),
    SOURCE_ITEM_CAT_ID      VARCHAR(36) not null
        constraint FK_SOURCE_ITEM_CAT_ID
            references BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY,
    SOURCE_ITEM_CNAME       VARCHAR(255),
    SOURCE_ITEM_ENAME       VARCHAR(255),
    NCV                     DECIMAL(24, 6),
    NCV_UNIT                VARCHAR(255),
    C_CONTENT               DECIMAL(24, 6),
    C_CONTENT_UNIT          VARCHAR(255),
    CO2_CONTENT             DECIMAL(24, 6),
    CO2_CONTENT_UNIT        VARCHAR(255),
    OXIDATION_RATE          DECIMAL(24, 6),
    EF                      DECIMAL(24, 6),
    EF_OXIDATION            DECIMAL(24, 6),
    EF_UNIT                 VARCHAR(255),
    USING_NG_CARBON_CONTENT BOOLEAN      default FALSE,
    REMARK                  VARCHAR(255),
    REC_CREATOR             VARCHAR(255) default 'admin',
    REC_CREATE_TIME         TIMESTAMP(6) default CURRENT TIMESTAMP,
    REC_REVISOR             VARCHAR(255),
    REC_REVISE_TIME         TIMESTAMP(6)
)
    distribute by hash (EMISSION_FACTOR_ID);

comment on table BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY is '排放因子库';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.EMISSION_FACTOR_ID is '排放因子ID';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.EMISSION_FACTOR_CODE is '排放因子代码';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.SOURCE_ITEM_CAT_ID is '排放因子分类ID';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.SOURCE_ITEM_CNAME is '因子来源物料中文名';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.SOURCE_ITEM_ENAME is '因子来源物料英文名';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.NCV is '低位发热量';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.NCV_UNIT is '低位发热量单位';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.C_CONTENT is '含碳量';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.C_CONTENT_UNIT is '含碳量单位';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.OXIDATION_RATE is '碳氧化率';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.EF is '碳排放因子';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.EF_OXIDATION is '碳排放因子（计算碳氧化率）';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.EF_UNIT is '碳排放因子单位';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.REMARK is '备注';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.REC_CREATOR is '记录创建人';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.REC_CREATE_TIME is '记录创建时间';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.REC_REVISOR is '记录修改人';

comment on column BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY.REC_REVISE_TIME is '记录修改时间';


