create view BG00MAC102.V_ADS_EMISSION_FACTOR_CATEGORY as
select cat.SOURCE_ITEM_CAT_ID,
       cat.SOURCE_DOC_ID,
       doc.DATE_OF_ISSUE,
       doc.VALID_FROM,
       doc.VALID_UNTIL,
       doc.SOURCE_CODE,
       doc.SOURCE_NAME,
       doc.SOURCE_DOC_NAME,
       doc.IS_VALID,
       cat.SOURCE_ITEM_MAIN_CAT_CODE,
       cat.SOURCE_ITEM_MAIN_CAT_NAME,
       cat.SOURCE_ITEM_SUB_CAT_CODE,
       cat.SOURCE_ITEM_SUB_CAT_NAME,
       cat.IS_PRODUCTION,
       cat.REC_CREATOR,
       cat.REC_CREATE_TIME,
       cat.REC_REVISOR,
       cat.REC_REVISE_TIME
from BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY cat
         join BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC doc
              on cat.SOURCE_DOC_ID = doc.SOURCE_DOC_ID;

select *
from V_ADS_EMISSION_FACTOR_CATEGORY;


CREATE VIEW BG00MAC102.V_ADS_EMISSION_FACTOR_LIBRARY AS
SELECT LIB.EMISSION_FACTOR_ID,
       LIB.EMISSION_FACTOR_CODE,
       DOC.SOURCE_DOC_ID,
       DOC.DATE_OF_ISSUE,
       DOC.VALID_FROM,
       DOC.VALID_UNTIL,
       DOC.SOURCE_CODE,
       DOC.SOURCE_NAME,
       DOC.SOURCE_DOC_NAME,
       DOC.SOURCE_DOC_CODE,
       DOC.IS_VALID,
       DOC.IS_MIGRATED,
       CAT.SOURCE_ITEM_CAT_ID,
       CAT.SOURCE_ITEM_MAIN_CAT_CODE,
       CAT.SOURCE_ITEM_MAIN_CAT_NAME,
       CAT.SOURCE_ITEM_SUB_CAT_CODE,
       CAT.SOURCE_ITEM_SUB_CAT_NAME,
       CAT.IS_PRODUCTION,
       LIB.SOURCE_ITEM_CNAME,
       LIB.SOURCE_ITEM_ENAME,
       LIB.NCV,
       LIB.NCV_UNIT,
       LIB.C_CONTENT,
       LIB.C_CONTENT_UNIT,
       LIB.CO2_CONTENT,
       LIB.CO2_CONTENT_UNIT,
       LIB.OXIDATION_RATE,
       LIB.EF,
       LIB.EF_OXIDATION,
       LIB.EF_UNIT,
       LIB.USING_NG_CARBON_CONTENT,
       LIB.REMARK,
       LIB.REC_CREATOR,
       LIB.REC_CREATE_TIME,
       LIB.REC_REVISOR,
       LIB.REC_REVISE_TIME
FROM BG00MAC102.T_ADS_FACT_EMISSION_FACTOR_LIBRARY LIB
         JOIN BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_CATEGORY CAT
              ON LIB.SOURCE_ITEM_CAT_ID = CAT.SOURCE_ITEM_CAT_ID
         JOIN BG00MAC102.T_ADS_DIM_EMISSION_FACTOR_SOURCE_DOC DOC
              ON CAT.SOURCE_DOC_ID = DOC.SOURCE_DOC_ID;


