create table BG00MAC102.T_ADS_FACT_LCA_SUBCLASS_EPD_MONTH_DEBUG
(
    PROC_NAME VARCHAR(128),
    STEP_DESC VARCHAR(256),
    VAR_VALUE VARCHAR(4000),
    LOG_TIME  TIMESTAMP(6)
)
    distribute by hash (PROC_NAME);

